version: "3.8"
services:

  db:
    image: postgres:latest
    network_mode: bridge
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fakng-db
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

#  fakng-agrgtr:
#    image: mhsl/fakng-agrgtr
#    network_mode: bridge
#    container_name: fakng-agrgtr
#    ports:
#      - 8081:8081
#    depends_on:
#      - db
#    links:
#      - db
#    environment:
#      DB_HOST: ${DB_HOST}
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#
#  fakng-ui:
#    image: mhsl/fakng-ui
#    network_mode: bridge
#    container_name: fakng-ui
#    ports:
#      - 80:80
#    depends_on:
#      - fakng-api
#    links:
#      - fakng-api

volumes:
  pgdata: